import { Sparkles } from 'lucide-react'
import { Card } from '@/components/ui/card'

interface DigestBullet {
  summary: string
  articleId: string
  articleTitle: string
}

// Mock daily digest — in production this would be generated by an AI service
const MOCK_DIGEST: { date: string; bullets: DigestBullet[] } = {
  date: '2026-03-18',
  bullets: [
    { summary: 'ASU Portal launches a new schedule-first enrollment system that eliminates time conflicts automatically.', articleId: 'n01', articleTitle: 'ASU Portal Launches New Online Enrollment System' },
    { summary: 'Midterm exams are scheduled for March 25-29 — students should check their exam schedules and bring IDs.', articleId: 'n02', articleTitle: 'Midterm Examination Schedule Released' },
    { summary: 'The tuition payment deadline has been extended to March 31 to give students more time.', articleId: 'n03', articleTitle: 'Payment Deadline Extended to March 31' },
  ],
}

interface NewsDigestProps {
  onSelectArticle: (articleId: string) => void
}

export function NewsDigest({ onSelectArticle }: NewsDigestProps) {
  return (
    <Card className="border-l-4 border-l-[var(--color-accent)]">
      <div className="flex items-center gap-2 mb-3">
        <Sparkles className="h-4 w-4 text-[var(--color-accent)]" />
        <h2 className="font-display text-sm font-bold text-[var(--color-text-primary)]">
          Today&apos;s Digest
        </h2>
        <span className="text-[10px] text-[var(--color-text-secondary)]">
          {new Date(MOCK_DIGEST.date).toLocaleDateString('en-PH', { month: 'short', day: 'numeric' })}
        </span>
      </div>
      <ul className="space-y-2">
        {MOCK_DIGEST.bullets.map((bullet, i) => (
          <li key={i}>
            <button
              type="button"
              onClick={() => onSelectArticle(bullet.articleId)}
              className="w-full text-left rounded-[var(--radius-md)] px-3 py-2 hover:bg-[var(--color-bg)] transition-colors"
            >
              <p className="text-sm text-[var(--color-text-primary)]">{bullet.summary}</p>
              <p className="mt-0.5 text-[10px] text-[var(--color-accent)] hover:underline">
                Read: {bullet.articleTitle}
              </p>
            </button>
          </li>
        ))}
      </ul>
      <p className="mt-2 text-center text-[10px] text-[var(--color-text-secondary)]">
        AI-generated summary — tap to read full articles
      </p>
    </Card>
  )
}
